### PR TITLE
Add Unit formation drawing

### LINKED ISSUE #10: Add Drawing Formations for player units

### LINKED ISSUE #11: Create a BattleManager class for all entities

### PR DESCRIPTION
**Pull request by hsven**
Closes #10, closes #11
Also fixes a bug regarding EnemyUnit targeting the closest PlayerUnit, where sometimes they'd stop in place instead of pursuing, and adds prefabs for player and enemy units

### CODE REVIEW

**Review by lucas-mrq — COMMENTED** [review]
Code looks ok, but I'm failing creating the shapes to test

**Comment by hsven** [comment]
Sorry, should have mentioned the controls.
Hold down the left Alt key, and then press LMB and drag to create the shape.

**Review by lucas-mrq — APPROVED** [review]
Nice work, I think it will need improvements but it's looking nice for a Prototype

**Comment by guidzo99** [comment]
Code is tested and approved

**Pull request merged**
